nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['http://localhost:4200', 'http://127.0.0.1:4200']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    expose_headers: ['Authorization']
    max_age: 3600

  paths:
    '^/api/':
      allow_origin: ['http://localhost:4200', 'http://127.0.0.1:4200']
      allow_headers: ['Content-Type', 'Authorization']
      allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
      allow_credentials: true
      max_age: 3600
