nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:4200', 'http://127.0.0.1:4200']
    allow_methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
    allow_headers: ['Content-Type','Authorization']
    expose_headers: ['Link','Content-Range']
    max_age: 3600
    allow_credentials: true

  paths:
    '^/api/':
      allow_origin: ['http://localhost:4200', 'http://127.0.0.1:4200']
      allow_methods: ['GET','POST','PUT','PATCH','DELETE','OPTIONS']
      allow_headers: ['Content-Type','Authorization']
      expose_headers: ['Link','Content-Range']
      max_age: 3600
      allow_credentials: true

