# config/services.yaml

parameters: { }

services:
    # Config por defecto
    _defaults:
        autowire: true
        autoconfigure: true

    # ðŸ‘‡ REGISTRA TODOS LOS CONTROLADORES COMO CONTROLLER SERVICES
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # ðŸ‘‡ Resto de servicios de la app
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Si tenÃ©s servicios puntuales, van acÃ¡ abajo
    # App\Algo\MiServicio:
    #     arguments: ['@otro_servicio']
